# Generated by Django 3.0.8 on 2020-08-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200804_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
