# Generated by Django 3.0.8 on 2020-08-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_character_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ready',
            field=models.TextField(blank=True),
        ),
    ]
