# Generated by Django 3.0.8 on 2020-08-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='roles',
            field=models.TextField(default='werewolf,villager,villager,villager'),
        ),
    ]
