# Generated by Django 3.0.8 on 2020-08-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupchat_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='ready_count',
            field=models.IntegerField(default=0),
        ),
    ]
