# Generated by Django 3.0.8 on 2020-08-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupchat_ready_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='ready_count',
        ),
    ]
