# Generated by Django 3.0.8 on 2020-08-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='turn',
            field=models.TextField(default='villager'),
        ),
    ]
