# Generated by Django 3.0.8 on 2020-08-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_groupchat_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('turn', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='turn',
        ),
    ]
