# Generated by Django 3.0.8 on 2020-08-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200813_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='villager_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='werewolf_num',
            field=models.IntegerField(default=1),
        ),
    ]
