# Generated by Django 3.0.8 on 2020-08-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200814_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.TextField(default=''),
        ),
    ]
