# Generated by Django 3.0.8 on 2020-08-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_game_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='option_four',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='choice',
            name='option_four_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='votes',
            field=models.TextField(default='0000'),
        ),
    ]
