# Generated by Django 3.0.8 on 2020-08-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20200819_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='villager_num',
            field=models.IntegerField(default=3),
        ),
    ]
